version: '2'
services:
  postgres:
    image: mdillon/postgis:9.6
    ports:
      - 15432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "50"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aetrapp
      - POSTGRES_USER=aetrapp
      - POSTGRES_PASSWORD=aetrapp
  app:
    build: .
    # Use npm start in production
    command: nodemon src/
    links:
      - postgres
    ports:
    - 3030:3030
    volumes:
    # Development volumes. Comment-out for production
    - /src/node_modules
    - .:/src
    # Uncomment below for production (persist app data)
    # - ./.data/files:/src/files
    # - ./.data/public:/src/public
    environment:
      NODE_ENV: development
      NODE_CONFIG: |-
        {
          "siteUrl": "http://192.168.1.32:3030",
          "ipsUrl": "http://192.168.1.32:3131"
        }
